import Head from 'next/head';
import Link from 'next/link';
import { Fragment } from 'react';

export default function Test() {
	return (
		<Fragment>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>Test page</h1>
				<Link href='/'>Go to Home</Link>
			</main>

		</Fragment >
	)
}