import { promises as fs } from 'fs'
import path from 'path'
import Head from 'next/head';
import Link from 'next/link';
import { Fragment } from 'react';
import { GetStaticProps, GetStaticPropsContext } from 'next'
import { ReadFile } from 'src/utils/readJSON';

interface StaticProps {
	content: Data
	context: any
}

interface Props {

}

export default function Test({
	content,
	context,
}: StaticProps & Props) {

	console.log('context', context)

	return (
		<Fragment>
			<Head>
				<title>Next.js Test</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{JSON.stringify(content)}
			</main>

		</Fragment >
	)
}

interface Data {
	test1: string
	test2: string
	test3: string
}

export const getStaticProps: GetStaticProps = async ({
	locale = {},
	locales = [],
	params = {},
	preview = false,
	defaultLocale = {},
	previewData = {}
}) => {

	const data = await ReadFile.JSON<Data>('src/pages/test/data.json')

	return {
		props: {
			content: data,
			context: {
				locale,
				locales,
				params,
				preview,
				defaultLocale,
				previewData,
			}
		},
		revalidate: 1
	}
}